/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "CreateComplaint": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "DATABASE_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GetComplaint": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "ListComplaints": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "NormalComplaintsQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}